apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo-deployment
  labels:
    app: server-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: server-demo
  template:
    metadata:
      labels:
        app: server-demo
    spec:
      containers:
        - name: server-demo
          image: server:dev
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: server-demo-service
  labels:
    app: server-demo
spec:
  type: NodePort
  selector:
    app: server-demo
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
      nodePort: 30007
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: server-demo-service-ingress
#   labels:
#     app: server-demo
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /api
#             pathType: Prefix
#             backend:
#               service:
#                 name: server-demo-service
#                 port:
#                   number: 8080
